// Generated by lib/site-data/generate.mjs from composer.json "data" and the
// data/ folder at build time. Do not edit and do not commit: the next build
// rewrites it. base_sdk installs the neutral form (backend mode, no files).

import type { SiteDataBundle } from "./kinds";

export const SITE_DATA: SiteDataBundle = {
  "mode": "backend",
  "files": {}
};
